In [1]:
import tensorflow as tf

2.5.0


In [14]:
# Initialization of Tensors
x = tf.constant(5, shape=(1, 1), dtype=tf.float32)
x = tf.constant([[1, 2, 3], [4, 5, 6]])
x = tf.ones((3, 3))
x = tf.zeros((2, 3))
x = tf.eye(3) # I for identity matrix
x = tf.random.normal((3, 3), mean=0, stddev=1)
x = tf.random.uniform((1, 3), minval=0, maxval=1)
x = tf.range(9)
x = tf.range(start=1, limit=10, delta=2)
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [23]:
#Mathematical Operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = tf.add(x, y)
z = x + y
print(z)

z = tf.subtract(x, y)
z = x - y
print(z)

z = tf.divide(x, y)
z = x / y
print(z)

z = tf.multiply(x, y)
z = x * y
print(z)

z = tf.tensordot(x, y, axes= 1)
z = tf.reduce_sum(x*y, axis=0)
print(z)

z = x ** 5
print(z)

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0.47075135  2.5812993  -0.85917896  0.13152851]
 [ 4.0441427   0.15149105  2.2373548  -1.4562263 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.47075135  2.5812993  -0.85917896  0.13152851]
 [ 4.0441427   0.15149105  2.2373548  -1.4562263 ]], shape=(2, 4), dtype=float32)


In [32]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1: 3])
print(x[: : 2])
print(x[::-1])

indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

print(x[0, :])
print(x[0:2, :])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [35]:
# Reshaping
x = tf.range(9)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
